# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89,…
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

import sys

lim = int(sys.argv[1])
even_sum = 0
fib_old, fib_new = 0, 1
while fib_old < lim:
#    print(fib_old)
    fib_old, fib_new = fib_new, fib_new + fib_old
    if fib_new % 2 == 0:
        even_sum += fib_new
#        print(fib_old,fib_new,even_sum)
print(even_sum)